data:
  block_size: 240
  duration: 2
  sampling_rate: 22050
  # f1 full
  train_path: /work/jgtf0322/Homework/2023-Fall-DLMAG/HW2/dataset/train
  valid_path: /work/jgtf0322/Homework/2023-Fall-DLMAG/HW2/dataset/valid

model:
  n_mag_harmonic: 256
  n_mag_noise: 80
  n_harmonics: 150
loss:
  n_ffts: [1024, 512, 256, 128]
device: cuda
env:
  expdir: /work/jgtf0322/Homework/2023-Fall-DLMAG/HW2/exp/Full
  # expdir: exp/m1-full/sawsinsub-256
  # expdir: exp/f1-3min/sawsinsub-256
  # expdir: exp/m1-3min/sawsinsub-256
  gpu: 0
  gpu_id: 0
inference:
  batch_size: 1
train:
  batch_size: 32
  epochs: 100000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002
